# Generated by Django 5.0.2 on 2024-03-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_state", models.TextField()),
                (
                    "game_status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("FINISHED", "Finished"),
                        ],
                        default="IN_PROGRESS",
                        max_length=11,
                    ),
                ),
                (
                    "current_turn",
                    models.CharField(
                        choices=[("WHITE", "White"), ("BLACK", "Black")],
                        default="WHITE",
                        max_length=5,
                    ),
                ),
                ("move_log", models.TextField(blank=True)),
            ],
        ),
    ]
