# Generated by Django 5.0.2 on 2024-03-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black')], db_index=True, default='WHITE', max_length=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='move_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
